name: CI - zoro-lib

on:
  push:
    branches: [main]
    paths:
      - "packages/**"
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: check linting
        run: pnpm run lint

      - name: check formatting
        run: pnpm run fmt:check
